DROP TABLE IF EXISTS settings
DROP TABLE IF EXISTS images
DROP TABLE IF EXISTS quotes
DROP TABLE IF EXISTS authors

CREATE TABLE settings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  world TEXT NOT NULL,
  content: TEXT NOT NULL
)

CREATE TABLE images (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  world TEXT NOT NULL,
  content: TEXT NOT NULL
)

CREATE TABLE quotes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  world TEXT NOT NULL,
  content: TEXT NOT NULL
)

CREATE TABLE authors (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  world TEXT NOT NULL,
  content: TEXT NOT NULL
)
